version: "3.8"

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: bikeapplicationdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data-local:/var/lib/postgresql/data

volumes:
  postgres-data-local:
    driver: local
